Repository RealShadowNova/joshdb-providers, pull requests merged in 2022-01, with the labels that each got.

#8 feat(ci): add mongo build
  .github/workflows/continuous-delivery.yml
Labels: Meta: GitHub, Priority: High, SEM: N/A

#10 feat(json): implement JSONProvider
  .github/workflows/continuous-delivery.yml
  .gitignore
  package.json
  packages/json/jest.config.ts
  packages/json/package.json
  packages/json/src/index.ts
  packages/json/src/lib/ChunkHandler.ts
  packages/json/src/lib/File.ts
  packages/json/src/lib/JSONProvider.ts
  packages/json/src/lib/JSONProviderError.ts
  packages/json/src/lib/chunk-files/ChunkFile.ts
  packages/json/src/lib/chunk-files/ChunkIndexFile.ts
  packages/json/src/lib/chunk-files/ChunkLockFile.ts
  packages/json/src/tsconfig.json
  packages/json/tests/lib/ChunkHandler.test.ts
  packages/json/tests/lib/File.test.ts
  packages/json/tests/lib/JSONProvider.test.ts
  packages/json/tests/tsconfig.json
  packages/json/tsconfig.base.json
  packages/json/tsconfig.eslint.json
  yarn.lock
Labels: Priority: High, SEM: N/A, Status: Review Ready, Type: Provider

#13 refactor(mongo): remove uuid in favor of objectId for autoKey
  packages/mongo/package.json
  packages/mongo/src/lib/MongoProvider.ts
Labels: Meta: Refactor, Priority: High, SEM: Major, Status: Ready To Merge, Type: Needs Rebase & Merge, Type: Provider

#11 feat(tests): implement base tests for providers
  packages/json/src/lib/JSONProvider.ts
  packages/json/tests/lib/JSONProvider.test.ts
  packages/mongo/tests/lib/MongoProvider.test.ts
  tests/runProviderTest.ts
  tests/tsconfig.json
  tsconfig.eslint.json
  yarn.lock
Labels: Priority: Medium, SEM: N/A, Status: WIP, Type: Provider

#15 feat(build): add UMD bundles
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  package.json
  packages/json/package.json
  packages/json/rollup.bundle.ts
  packages/mongo/package.json
  packages/mongo/rollup.bundle.ts
  scripts/rollup.bundle.ts
  tsconfig.base.json
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: Feature, Priority: High, SEM: N/A, Status: Review Ready

#17 chore(tests): update setMany() provider test
  tests/runProviderTest.ts
Labels: Priority: High, SEM: N/A, Status: Review Ready, Type: Maintenance

#18 chore(mongo): update setMany() method
  packages/mongo/src/lib/MongoProvider.ts
Labels: Priority: Medium, Status: Review Ready, Type: Maintenance

#16 chore(json): update setMany() method
  packages/json/src/lib/JSONProvider.ts
Labels: Priority: Medium, SEM: N/A, Status: Review Ready, Type: Maintenance

#19 chore(monorepo): remove lerna
  lerna.json
  package.json
  yarn.lock
Labels: Priority: Medium, SEM: N/A, Status: Review Ready, Type: Enhancement

#20 feat(docs): update guide with script tool
  .gitignore
  docs/ContributingYourOwnProvider.md
  docs/ContributingYourOwnProvider/GettingStarted.md
  package.json
  scripts/generate/generate.mjs
  scripts/generate/jobs.mjs
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: Documentation, Priority: High, SEM: N/A, Status: Review Ready
